### ISSUE TITLE
Fix the names as they are misleading

### ISSUE THREAD

**Issue by maxwroc** [simondoescode/delay.css#1]
Milli means 10^-3 so 1s and 1ms is 1.001s not 1.1s
```CSS
.delay1s1ms {
  animation-delay: 1.1s;
  -moz-animation-delay: 1.1s;
  -webkit-animation-delay: 1.1s;
  -o-animation-delay: 1.1s;
  transition-delay: 1.1s;
  -webkit-transition-delay: 1.1s;
  -moz-transition-delay: 1.1s;
  -o-transition-delay: 1.1s;
}
```
